### ISSUE TITLE
Unable to search Repositories

### ISSUE THREAD

**Issue by Reakwon87** [kodil/kodil#30]
Am unable to find Kodil when searching GitHib by Username in GitBrowser. Receiving #1 - GitBrowser Error: Please check the log for more info. #2 - No Results Found: Review Search Terms

Am able to search any and all others, with no issues. 

Log Snippet:
[gitbrokodil.txt](https://github.com/kodil/kodil/files/1922753/gitbrokodil.txt)

**Comment by Reakwon87** [comment]
Am unable to find Kodil when searching GitHib by Username in GitBrowser. Receiving #1 - GitBrowser Error: Please check the log for more info. #2 - No Results Found: Review Search Terms

Am able to search any and all others, with no issues. 

Log Snippet:

-->End of Python script error report<--
23:12:21.524 T:1945096192   ERROR: GetDirectory - Error getting plugin://plugin.git.browser/?mode=search&query=kodil&type=username
23:12:21.524 T:1945096192   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.git.browser/?mode=search&query=kodil&type=username) failed
23:13:19.537 T:1945096192   ERROR: GetDirectory - Error getting plugin://plugin.git.browser/?mode=addon_settings
23:13:19.537 T:1945096192   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.git.browser/?mode=addon_settings) failed
23:13:25.997 T:1668281248  NOTICE: Git Browser: Executing with args: {'type': 'username', 'mode': 'search_menu', 'title': 'Search by GitHub Username'}
23:13:31.691 T:1668281248  NOTICE: Git Browser: Returning cached response
23:13:37.983 T:1668281248  NOTICE: Previous line repeats 8 times.
23:13:37.983 T:1668281248  NOTICE: Git Browser: {"message":"Only the first 1000 search results are available","documentation_url":"https://developer.github.com/v3/search/"}
23:13:38.053 T:1668281248   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object has no attribute '__getitem__'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.git.browser/addon.py", line 187, in <module>
                                                if __name__ == '__main__': kodi.run()
                                              File "/storage/.kodi/addons/plugin.git.browser/libs/kodi.py", line 418, in run
                                                __dispatcher[args['mode']]()
                                              File "/storage/.kodi/addons/plugin.git.browser/addon.py", line 57, in search
                                                response = github_api.find_zips(q)
                                              File "/storage/.kodi/addons/plugin.git.browser/libs/github_api.py", line 145, in find_zips
                                                results = limit_versions(call("/search/code", query={"per_page": page_limit, "q":"user:%s+filename:*.zip" % user}, cache_limit=1))
                                              File "/storage/.kodi/addons/plugin.git.browser/libs/github_api.py", line 248, in call
                                                results['items'] += temp['items']
                                            TypeError: 'NoneType' object has no attribute '__getitem__'
                                            -->End of Python script error report<--

**Comment by danny1990** [comment]
The addons here are outdated and a lot of them are not being updated anymore.

For Github Browser you should install the tvaddons repo from https://www.tvaddons.co. If the problem persist you can post on their forum.
