### ISSUE TITLE
captcha error?

### ISSUE THREAD

**Issue by zen-aglasman** [kodil/kodil#5]
Getting new errors (everything was working fine).
i can see that  hash=re.findall('noscript\?k\=(.*?)"',body)[0] is out of array boundaries.
anyone can pls help?

18:35:38 120228.921875 T:1291842464   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.sdarot.tv/sdarottv.py", line 254, in <module>
                                                MAIN_MENU()
                                              File "/storage/.kodi/addons/plugin.video.sdarot.tv/sdarottv.py", line 61, in MAIN_MENU
                                                page = getData(DOMAIN+'/series',referer=DOMAIN)
                                              File "/storage/.kodi/addons/plugin.video.sdarot.tv/resources/lib/sdarotcommon.py", line 230, in getData
                                                return getData_attempt(url, timeout, name, postData,referer)
                                              File "/storage/.kodi/addons/plugin.video.sdarot.tv/resources/lib/sdarotcommon.py", line 186, in getData_attempt
                                                response = cloudflare.ddos_open(url=req,timeout=180,data=postData)
                                              File "/storage/.kodi/addons/plugin.video.sdarot.tv/resources/lib/cloudflare.py", line 26, in ddos_open
                                                return ddos_open_with(_dummy_opener, url, data, timeout)
                                              File "/storage/.kodi/addons/plugin.video.sdarot.tv/resources/lib/cloudflare.py", line 64, in ddos_open_with
                                                hash=re.findall('noscript\?k\=(.*?)"',body)[0]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
18:35:38 120229.054688 T:1963888640   ERROR: GetDirectory - Error getting plugin://plugin.video.sdarot.tv/
18:35:38 120229.054688 T:1963888640   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.sdarot.tv/) failed

**Comment by mikiha** [comment]
we are not the plugin developers
